name: Update Roadmap

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-roadmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get install imagemagick

      - name: Download Roadmap Image
        run: |
          curl -L -o roadmap.png "https://roadmap.sh/card/wide/66b06abcc3e10bac2503fea1?variant=dark"
          head -n 20 roadmap.png  # Print the first 20 lines of the downloaded file to check its content

      - name: Verify Image
        run: |
          file roadmap.png
          identify roadmap.png

      - name: Commit and Push Changes
        run: |
          git config --local user.email "iyakaremyejan@gmail.com"
          git config --local user.name "Janvier Iyakaremye"
          git add roadmap.png
          git diff-index --quiet HEAD || git commit -m "Update roadmap"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
