name: Update README with Timestamp

on:
  schedule:
    # Runs every day at midnight UTC. Adjust the schedule as needed.
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow.

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with current timestamp
        run: |
          # Generate the current timestamp
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          
          # Replace the timestamp in README.md
          sed -i "s/timestamp=[0-9]*/timestamp=${TIMESTAMP}/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with new timestamp ${TIMESTAMP}"
          git push
