name: Update Roadmap

permissions:
  contents: write  # This allows the action to push changes to the repository

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow every day at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-roadmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get install imagemagick

      - name: Download Roadmap Image
        run: |
          curl -L -o roadmap.png "https://roadmap.sh/card/wide/66b06abcc3e10bac2503fea1?variant=dark"

      - name: Verify Image
        run: |
          file roadmap.png  # Check the file type to ensure it's a valid PNG
          identify roadmap.png  # Get image details using ImageMagick

      - name: Convert to SVG (If Downloaded Correctly)
        run: |
          if file roadmap.png | grep -q 'PNG image data'; then
            convert roadmap.png roadmap.svg
          else
            echo "Downloaded file is not a valid PNG image."
            exit 1
          fi

      - name: Commit and Push Changes
        run: |
          git config --local user.email "iyakaremyejan@gmail.com"
          git config --local user.name "Janvier Iyakaremye"
          git add roadmap.svg
          git diff-index --quiet HEAD || git commit -m "Update roadmap"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
